### PR TITLE
adminAddUserTest

### PR DESCRIPTION
**Pull request by kevdaci**
I added the tests for the admin to add a user to the system. I worked on the client side tests.

### CODE REVIEW

**Review by crodencorrent — DISMISSED** [review]
Tests aren't running at all, though they look fine - make sure that everything is defined properly. There are about 80 new linter errors from this file, some of which are claiming things aren't defined.

**Review by RyanClementsHax — CHANGES_REQUESTED** [review]
Every one of these changes is in marks review. Should I just consider his pull request?

**Comment by kevdaci** [comment]
@RyanClementsHax The exact same code is in Mark's review?

**Review by sjswanson — COMMENTED** [review]
This PR seems kinda out of date.  Do you know when you last rebased it?

**Pull request closed without merging**
