### PR TITLE
itemCounts

### PR DESCRIPTION
**Pull request by kevdaci**
Sam and I worked on displaying the status of the items and the item counts. We also deleted the routes admin routes for creating, updating, and deleting items since there already is a view and functionality for that. We also deleted some of the test files for the admin item routes, since we do not need them.

### CODE REVIEW

**Comment by crodencorrent** [comment]
I'm pretty confused by this PR - ostensibly, it's for displaying item counts, but I'm not seeing anywhere to view these, and there's also a mass of deletions in package-lock.json that isn't explained in the commit message.

**Comment by sjswanson** [comment]
@crodencorrent oops yeah I'm not sure what happened with the package-lock file but I just replaced it with what we currently have in develop.  It does show the item counts and working status on the list view.

**Comment by markd315** [comment]
I can't sign into this branch after checking it out so I can't review it :/

**Review by markd315 — CHANGES_REQUESTED** [review]
I was able to log into heroku. Please fix the categories and module dropdowns on the edit item pane and then this is ready for develop.

**Comment by sjswanson** [comment]
Ok I fixed the dropdowns and made a few more improvements

**Review by markd315 — APPROVED** [review]

**Pull request merged**
